// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace FDSY_Coded_UI_Test_Project
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Verifies breweries to be selected is rendered.
        /// </summary>
        public void VerifyBrewerySelectTest()
        {
            #region Variable Declarations
            HtmlHyperlink uIBeersHyperlink = this.UIHomePageSheridianFDYWindow.UIHomePageSheridianFDYDocument.UIBeersHyperlink;
            HtmlHyperlink uICreateNewHyperlink = this.UIHomePageSheridianFDYWindow.UIIndexSheridianFDYSKBDocument.UICreateNewHyperlink;
            #endregion

            // Click 'Beers' link
            Mouse.Click(uIBeersHyperlink, new Point(28, 24));

            // Click 'Create New' link
            Mouse.Click(uICreateNewHyperlink, new Point(46, 7));
        }
        
        #region Properties
        public UICreateSheridianFDYSKWindow UICreateSheridianFDYSKWindow
        {
            get
            {
                if ((this.mUICreateSheridianFDYSKWindow == null))
                {
                    this.mUICreateSheridianFDYSKWindow = new UICreateSheridianFDYSKWindow();
                }
                return this.mUICreateSheridianFDYSKWindow;
            }
        }
        
        public UIHomePageSheridianFDYWindow UIHomePageSheridianFDYWindow
        {
            get
            {
                if ((this.mUIHomePageSheridianFDYWindow == null))
                {
                    this.mUIHomePageSheridianFDYWindow = new UIHomePageSheridianFDYWindow();
                }
                return this.mUIHomePageSheridianFDYWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICreateSheridianFDYSKWindow mUICreateSheridianFDYSKWindow;
        
        private UIHomePageSheridianFDYWindow mUIHomePageSheridianFDYWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateSheridianFDYSKWindow : BrowserWindow
    {
        
        public UICreateSheridianFDYSKWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Create - Sheridian FDYSK Breweries and Sons";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Create - Sheridian FDYSK Breweries and Sons");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UICreateSheridianFDYSKDocument UICreateSheridianFDYSKDocument
        {
            get
            {
                if ((this.mUICreateSheridianFDYSKDocument == null))
                {
                    this.mUICreateSheridianFDYSKDocument = new UICreateSheridianFDYSKDocument(this);
                }
                return this.mUICreateSheridianFDYSKDocument;
            }
        }
        #endregion
        
        #region Fields
        private UICreateSheridianFDYSKDocument mUICreateSheridianFDYSKDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateSheridianFDYSKDocument : HtmlDocument
    {
        
        public UICreateSheridianFDYSKDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Create - Sheridian FDYSK Breweries and Sons";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Beers/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:6875/Beers/Create";
            this.WindowTitles.Add("Create - Sheridian FDYSK Breweries and Sons");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIBreweryBreweryIdComboBox
        {
            get
            {
                if ((this.mUIBreweryBreweryIdComboBox == null))
                {
                    this.mUIBreweryBreweryIdComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIBreweryBreweryIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "BreweryBreweryId";
                    this.mUIBreweryBreweryIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "BreweryBreweryId";
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "BreweryBreweryId";
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "11";
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"BreweryBreweryId\" class=\"form-cont";
                    this.mUIBreweryBreweryIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIBreweryBreweryIdComboBox.WindowTitles.Add("Create - Sheridian FDYSK Breweries and Sons");
                    #endregion
                }
                return this.mUIBreweryBreweryIdComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIBreweryBreweryIdComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageSheridianFDYWindow : BrowserWindow
    {
        
        public UIHomePageSheridianFDYWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - Sheridian FDYSK Breweries and Sons";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - Sheridian FDYSK Breweries and Sons");
            this.WindowTitles.Add("Index - Sheridian FDYSK Breweries and Sons");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageSheridianFDYDocument UIHomePageSheridianFDYDocument
        {
            get
            {
                if ((this.mUIHomePageSheridianFDYDocument == null))
                {
                    this.mUIHomePageSheridianFDYDocument = new UIHomePageSheridianFDYDocument(this);
                }
                return this.mUIHomePageSheridianFDYDocument;
            }
        }
        
        public UIIndexSheridianFDYSKBDocument UIIndexSheridianFDYSKBDocument
        {
            get
            {
                if ((this.mUIIndexSheridianFDYSKBDocument == null))
                {
                    this.mUIIndexSheridianFDYSKBDocument = new UIIndexSheridianFDYSKBDocument(this);
                }
                return this.mUIIndexSheridianFDYSKBDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageSheridianFDYDocument mUIHomePageSheridianFDYDocument;
        
        private UIIndexSheridianFDYSKBDocument mUIIndexSheridianFDYSKBDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageSheridianFDYDocument : HtmlDocument
    {
        
        public UIHomePageSheridianFDYDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - Sheridian FDYSK Breweries and Sons";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:6875/";
            this.WindowTitles.Add("Home Page - Sheridian FDYSK Breweries and Sons");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBeersHyperlink
        {
            get
            {
                if ((this.mUIBeersHyperlink == null))
                {
                    this.mUIBeersHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBeersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBeersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBeersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBeersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Beers";
                    this.mUIBeersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Beers";
                    this.mUIBeersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBeersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:6875/Beers";
                    this.mUIBeersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBeersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Beers\"";
                    this.mUIBeersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIBeersHyperlink.WindowTitles.Add("Home Page - Sheridian FDYSK Breweries and Sons");
                    #endregion
                }
                return this.mUIBeersHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBeersHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexSheridianFDYSKBDocument : HtmlDocument
    {
        
        public UIIndexSheridianFDYSKBDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Sheridian FDYSK Breweries and Sons";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Beers";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:6875/Beers";
            this.WindowTitles.Add("Index - Sheridian FDYSK Breweries and Sons");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICreateNewHyperlink
        {
            get
            {
                if ((this.mUICreateNewHyperlink == null))
                {
                    this.mUICreateNewHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Create New";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Beers/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:6875/Beers/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Beers/Create\"";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUICreateNewHyperlink.WindowTitles.Add("Index - Sheridian FDYSK Breweries and Sons");
                    #endregion
                }
                return this.mUICreateNewHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICreateNewHyperlink;
        #endregion
    }
}
